<?php
/**
 * Plugin URL:      https://wordpress.org/plugins/cf-image-resizing/
 * Author:          Mecanik1337
 * Author URL:      https://mecanik.dev/en/
 *
 * AUTOMATICALLY GENERATED.
 * DO NOT EDIT THIS FILE MANUALLY UNLESS YOU KNOW WHAT YOU ARE DOING.
 */

// Exit if accessed directly
if (!defined('ABSPATH')) {
    exit; 
}

if(!defined('CF_IMAGE_RESIZING_SITE_URL')) {
    define('CF_IMAGE_RESIZING_SITE_URL', '');
}

if(!defined('CF_IMAGE_RESIZING_SITE_FOLDER')) {
    define('CF_IMAGE_RESIZING_SITE_FOLDER', '');
}

if(!defined('CF_IMAGE_RESIZING_HOME_DIR')) {
    define('CF_IMAGE_RESIZING_HOME_DIR', '');
}

/******************************************************************************/
define('CF_IMAGE_RESIZING_HOOK_1', TRUE);
define('CF_IMAGE_RESIZING_HOOK_2', TRUE);
define('CF_IMAGE_RESIZING_HOOK_3', FALSE);
define('CF_IMAGE_RESIZING_HOOK_4', FALSE);
define('CF_IMAGE_RESIZING_HOOK_5', FALSE);
define('CF_IMAGE_RESIZING_HOOK_6', TRUE);

/******************************************************************************/
define('CF_IMAGE_RESIZING_FIT', 'crop');
define('CF_IMAGE_RESIZING_QUALITY', 80);
define('CF_IMAGE_RESIZING_FORMAT', 'auto');
define('CF_IMAGE_RESIZING_ONERROR', 'redirect');
define('CF_IMAGE_RESIZING_METADATA', 'none');

/******************************************************************************/
define('CF_IMAGE_RESIZING_STRIP_SIZES', TRUE);
define('CF_IMAGE_RESIZING_ADD_MISSING_SIZES', TRUE);
define('CF_IMAGE_RESIZING_FIX_VC_COMPOSER', FALSE);

/******************************************************************************/
define('CF_IMAGE_RESIZING_WHITELIST', FALSE);
define('CF_IMAGE_RESIZING_WHITELIST_URLS', [ 'fbcdn.net', 'twimg.com', 'cdninstagram.com', 'paypalobjects.com' ]);